package com.semdatex.catalogs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OpsCodesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpsCodesAllPropertiesEquals(OpsCodes expected, OpsCodes actual) {
        assertOpsCodesAutoGeneratedPropertiesEquals(expected, actual);
        assertOpsCodesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpsCodesAllUpdatablePropertiesEquals(OpsCodes expected, OpsCodes actual) {
        assertOpsCodesUpdatableFieldsEquals(expected, actual);
        assertOpsCodesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpsCodesAutoGeneratedPropertiesEquals(OpsCodes expected, OpsCodes actual) {
        assertThat(expected)
            .as("Verify OpsCodes auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpsCodesUpdatableFieldsEquals(OpsCodes expected, OpsCodes actual) {
        assertThat(expected)
            .as("Verify OpsCodes relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOpsCodesUpdatableRelationshipsEquals(OpsCodes expected, OpsCodes actual) {}
}
